#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# --- diagnostics state ------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APPIMAGE=""    # path to the .AppImage under test (positional arg, auto-detected, or asked)
LOG_FILE=""    # the single log artifact the maintainer reads
GST_SYS_DIR="" # system GStreamer plugin dir (candidate 4)
APP_PID=0      # pid of the app launched for the current run (its process group)
RUN_TMP=""     # per-run output capture
SIGNATURES='EGL_BAD_PARAMETER|symbol lookup error|SIGBUS|bwrap:|Failed to create GBM device|GStreamer element appsink not found'
VERDICTS=()

# The GStreamer candidate needs a system plugin dir; when none is found the
# run is skipped, so the advertised stage count shrinks (adjusted below,
# after the helpers are defined).

log() { printf '%s\n' "$*" >>"$LOG_FILE"; }

# cleanup — never leave the tested app (or its WebKit children) running, even
# if the friend presses Ctrl-C mid-run.
cleanup() {
  if [[ -n "$APP_PID" && "$APP_PID" != 0 ]]; then
    kill -- "-$APP_PID" 2>/dev/null || true
  fi
  if [[ -n "$RUN_TMP" ]]; then
    rm -f "$RUN_TMP" || true
  fi
}
trap cleanup EXIT
trap 'exit 130' INT

# ask_verdict — strict y/n for the "did it render?" question.
ask_verdict() {
  local reply=""
  while true; do
    printf '  %sCan you see the Markdown editor content in the window?%s %s(yes/no)%s ' "$BOLD" "$RESET" "$DIM" "$RESET"
    read -r reply || return 1
    case "$reply" in
      [Yy]*) return 0 ;;
      [Nn]*) return 1 ;;
      *) warn "please answer y (yes) or n (no)" ;;
    esac
  done
}

# validate_appimage — type-2 AppImage magic ("AI\x02" at offset 8).
validate_appimage() {
  local f="$1" magic=""
  [[ -f "$f" ]] || return 1
  if command -v dd >/dev/null 2>&1 && command -v od >/dev/null 2>&1; then
    magic="$(dd if="$f" bs=1 skip=8 count=3 2>/dev/null | od -An -tx1 | tr -d ' \n')"
    [[ "$magic" == "414902" ]]
  else
    return 0 # cannot verify without dd/od; accept
  fi
}

# detect_gst_dir — locate the host GStreamer plugin dir for candidate 4.
detect_gst_dir() {
  local dir=""
  if command -v pkg-config >/dev/null 2>&1; then
    dir="$(pkg-config --variable=pluginsdir gstreamer-1.0 2>/dev/null || true)"
  fi
  if [[ -z "$dir" || ! -d "$dir" ]]; then
    dir=""
    for d in /usr/lib64/gstreamer-1.0 /usr/lib/x86_64-linux-gnu/gstreamer-1.0 \
             /usr/lib/aarch64-linux-gnu/gstreamer-1.0 /usr/lib/gstreamer-1.0; do
      if [[ -d "$d" ]] && compgen -G "$d/libgst*.so*" >/dev/null; then
        dir="$d"
        break
      fi
    done
  fi
  GST_SYS_DIR="$dir"
}

# appimage_processes — any running Markdown-Magic instance (AppImage or inner
# binary) that could confuse the friend about which window is the test. The
# wizard's own command line legitimately contains the AppImage path (argument),
# so its process and every ancestor are excluded — they are never a separate
# instance, and killing them would kill the wizard itself.
appimage_processes() {
  local p="$BASHPID" seen="" line="" pid="" skip=""
  while [[ -n "$p" && "$p" != "0" && "$p" != "1" ]]; do
    seen="$seen $p"
    p="$(ps -o ppid= -p "$p" 2>/dev/null | tr -d ' ')"
  done
  while IFS= read -r line; do
    pid="${line%% *}"
    skip=""
    for a in $seen; do
      if [[ "$a" == "$pid" ]]; then
        skip=1
        break
      fi
    done
    if [[ -z "$skip" ]]; then
      printf '%s\n' "$line"
    fi
  done < <(pgrep -af 'markdown-magic|Markdown-Magic' 2>/dev/null || true)
}

# capture_process_state — the process tree of the launched run (pgid-scoped,
# so the friend's other apps are never listed or killed).
capture_process_state() {
  local procs=""
  if ps -eo pid,pgid,stat,comm,args >/dev/null 2>&1; then
    procs="$(ps -eo pid,pgid,stat,comm,args 2>/dev/null | awk -v p="$APP_PID" '$2 == p' || true)"
  fi
  if [[ -z "$procs" ]] && command -v pgrep >/dev/null 2>&1; then
    procs="$(pgrep -a -g "$APP_PID" 2>/dev/null || true)"
  fi
  printf '%s' "$procs"
}

# run_candidate "Stage title" [ENV K=V ...] — launch the AppImage with the
# given env overrides, capture stderr + process state, record the verdict.
run_candidate() {
  local title="$1"
  shift
  local env_args=("$@")
  local desc="${env_args[*]}"
  local procs="" webkit_count="0" rc=0 verdict="no" matches="" first="" line=""

  stage "$title"
  say "Testing: $desc"
  say "A window will open. Look for the Markdown editor content (editor + preview)."
  note "A white/blank window with only the title bar is the bug — that counts as no."

  RUN_TMP="$(mktemp "${TMPDIR:-/tmp}/appimage-run-XXXXXX")"

  log ""
  log "=== Run: $title ==="
  log "candidate: $desc"
  log "command: env $desc setsid \"$APPIMAGE\""
  log "started: $(date '+%Y-%m-%d %H:%M:%S %z')"

  # launch in its own process group (setsid) so the cleanup can kill the app
  # and every WebKit child without touching anything else on the host
  setsid env "${env_args[@]}" "$APPIMAGE" >>"$RUN_TMP" 2>&1 &
  APP_PID=$!
  log "pid: $APP_PID"

  sleep 3
  pause "Wait for the app window (first run unpacks the AppImage — allow up to ~30 s). Press Enter when the window is visible, or after ~30 s."

  procs="$(capture_process_state)"
  log ""
  log "[process tree]"
  if [[ -n "$procs" ]]; then
    log "$procs"
    webkit_count="$(printf '%s\n' "$procs" | grep -acE 'WebKit(Web|Network|GPU)Process' || true)"
  else
    log "(no processes left — the app exited on its own before the verdict)"
    note "The app is no longer running — it probably crashed or closed itself. Answer no."
  fi
  if [[ "$webkit_count" -gt 0 ]]; then
    note "WebKit helper processes were running ($webkit_count found)."
  else
    note "No WebKit helper processes were running."
  fi

  if ask_verdict; then
    verdict="yes"
  else
    verdict="no"
  fi
  log "verdict: $verdict"
  VERDICTS+=("$title => $verdict")

  kill -- "-$APP_PID" 2>/dev/null || true
  rc=0
  wait "$APP_PID" 2>/dev/null || rc=$?
  if [[ "$rc" -eq 143 ]]; then
    log "exit: terminated by the wizard (SIGTERM) after the verdict"
  elif [[ "$rc" -gt 128 && "$rc" -le 192 ]]; then
    # wait status 128+N means death by signal N — a startup crash like SIGBUS
    # leaves no stderr, so the signal is the only signature in the log
    local sig="$((rc - 128))" signame="signal $sig"
    case "$sig" in
      4)  signame="SIGILL" ;;
      6)  signame="SIGABRT" ;;
      7)  signame="SIGBUS" ;;
      8)  signame="SIGFPE" ;;
      11) signame="SIGSEGV" ;;
      15) signame="SIGTERM" ;;
      31) signame="SIGSYS" ;;
    esac
    log "exit: $rc — the app died from $signame (crash signature for the maintainer)"
  else
    log "exit: $rc"
  fi

  log ""
  log "[output (stdout and stderr)]"
  sed 's/^/  /' "$RUN_TMP" >>"$LOG_FILE" || true
  log ""

  matches="$(grep -aE "$SIGNATURES" "$RUN_TMP" || true)"
  log "[failure signatures]"
  if [[ -n "$matches" ]]; then
    log "$matches"
    first="${matches%%$'\n'*}"
    note "Signature seen in output: $first"
  else
    log "(none of the known signatures appeared in the captured output)"
    note "No known failure signature in the captured output."
  fi
  log ""

  rm -f "$RUN_TMP"
  RUN_TMP=""
  APP_PID=0

  say "Result: $verdict"
}

# ── Stage 1: setup — locate the AppImage, detect the host, open the log ────
detect_gst_dir
if [[ -z "$GST_SYS_DIR" ]]; then
  TOTAL_STAGES=4
  SKIPPED+=("GStreamer candidate — no system GStreamer plugin dir found, so it can't be tested")
fi

banner "Markdown-Magic AppImage diagnostic"

stage "Setup — locate the AppImage"
say "This wizard tests the candidate fixes for the blank AppImage window,"
say "one at a time, and writes a single log for the maintainer."

if [[ $# -gt 0 ]]; then
  APPIMAGE="$1"
elif [[ -f "$SCRIPT_DIR/Markdown-Magic_1.1.3_amd64.AppImage" ]]; then
  APPIMAGE="$SCRIPT_DIR/Markdown-Magic_1.1.3_amd64.AppImage"
else
  for f in "$SCRIPT_DIR"/*.AppImage "$HOME"/Downloads/*.AppImage; do
    if [[ -f "$f" ]]; then
      APPIMAGE="$f"
      break
    fi
  done
fi
if [[ -z "$APPIMAGE" ]]; then
  ask APPIMAGE_PATH "Full path to the Markdown-Magic .AppImage file:"
  APPIMAGE="$APPIMAGE_PATH"
fi
if [[ -z "$APPIMAGE" || ! -f "$APPIMAGE" ]]; then
  warn "No AppImage found. Run this wizard from the folder that contains"
  warn "Markdown-Magic_1.1.3_amd64.AppImage, or pass its path as an argument."
  exit 1
fi

if ! validate_appimage "$APPIMAGE"; then
  warn "That file does not look like an AppImage. Double-check the path:"
  warn "  $APPIMAGE"
  exit 1
fi

if [[ ! -x "$APPIMAGE" ]]; then
  if chmod +x "$APPIMAGE" 2>/dev/null; then
    note "Made the AppImage executable."
  else
    warn "Could not make the AppImage executable — the runs will probably fail."
  fi
fi
if [[ "$(basename "$APPIMAGE")" != *1.1.3* ]]; then
  warn "The filename doesn't mention 1.1.3. This wizard targets the shipped"
  warn "v1.1.3 AppImage — proceeding anyway, but double-check the file."
fi

if ! command -v setsid >/dev/null 2>&1; then
  warn "The 'setsid' tool is missing — this wizard needs it to clean up the"
  warn "app after each test. Install util-linux, then run the wizard again."
  exit 1
fi

if [[ -n "$GST_SYS_DIR" ]]; then
  note "GStreamer system plugin dir: $GST_SYS_DIR"
else
  warn "No system GStreamer plugin dir found — the GStreamer candidate will be skipped."
fi

running="$(appimage_processes)"
if [[ -n "$running" ]]; then
  warn "A Markdown-Magic instance is already running — it would confuse the test."
  if confirm "Close it now so the tests start clean"; then
    while read -r pid _; do
      kill "$pid" 2>/dev/null || true
    done <<<"$running"
    sleep 1
  else
    say "Please close the app window yourself, then run this wizard again."
    exit 1
  fi
fi

LOG_FILE="$SCRIPT_DIR/appimage-diagnostic-$(date '+%Y%m%d-%H%M%S').log"
{
  printf 'Markdown-Magic AppImage diagnostic (issue 01)\n'
  printf 'run: %s\n' "$(date '+%Y-%m-%d %H:%M:%S %z')"
  printf 'host: %s\n' "$(uname -a 2>/dev/null || printf 'unknown')"
  printf 'session type: %s\n' "${XDG_SESSION_TYPE:-unknown}"
  printf 'desktop: %s\n' "${XDG_CURRENT_DESKTOP:-unknown}"
  printf 'wayland display: %s\n' "${WAYLAND_DISPLAY:-none}"
  printf 'x11 display: %s\n' "${DISPLAY:-none}"
  printf 'appimage: %s\n' "$APPIMAGE"
  printf 'appimage size: %s bytes\n' "$(stat -c %s "$APPIMAGE" 2>/dev/null || printf '?')"
  printf 'gstreamer system dir: %s\n' "${GST_SYS_DIR:-not detected}"
  if [[ -z "$GST_SYS_DIR" ]]; then
    printf 'candidate 4 (GStreamer): SKIPPED — no system plugin dir found; run 4/4 was not executed\n'
  fi
} >"$LOG_FILE"
note "Log: $LOG_FILE"

if [[ -n "$GST_SYS_DIR" ]]; then
  say "Plan — four runs, one candidate each:"
  step "1. APPIMAGE_EXTRACT_AND_RUN=1 — bypass the FUSE mount"
  step "2. + WEBKIT_DISABLE_COMPOSITING_MODE=1 — WebKitGTK paint bug"
  step "3. + WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1 — bubblewrap sandbox"
  step "4. + GST_PLUGIN_SYSTEM_PATH_1_0 — GStreamer plugin search path"
else
  say "Plan — three runs, one candidate each (GStreamer skipped):"
  step "1. APPIMAGE_EXTRACT_AND_RUN=1 — bypass the FUSE mount"
  step "2. + WEBKIT_DISABLE_COMPOSITING_MODE=1 — WebKitGTK paint bug"
  step "3. + WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1 — bubblewrap sandbox"
fi
pause "Ready to start the first run?"

# ── Stages 2–5: one candidate per run ──────────────────────────────────────
run_candidate "1/4 — extract-and-run (FUSE bypass)" \
  "APPIMAGE_EXTRACT_AND_RUN=1"

run_candidate "2/4 — compositing mode off" \
  "APPIMAGE_EXTRACT_AND_RUN=1" "WEBKIT_DISABLE_COMPOSITING_MODE=1"

run_candidate "3/4 — web process sandbox off" \
  "APPIMAGE_EXTRACT_AND_RUN=1" "WEBKIT_DISABLE_SANDBOX_THIS_IS_DANGEROUS=1"

if [[ -n "$GST_SYS_DIR" ]]; then
  run_candidate "4/4 — GStreamer plugin search path" \
    "APPIMAGE_EXTRACT_AND_RUN=1" "GST_PLUGIN_SYSTEM_PATH_1_0=$GST_SYS_DIR"
fi

# ── Closing summary ────────────────────────────────────────────────────────
log ""
log "=== Summary ==="
for v in "${VERDICTS[@]}"; do
  log "$v"
done
if (( ${#SKIPPED[@]} )); then
  log ""
  log "[not tested]"
  for s in "${SKIPPED[@]}"; do
    log "- $s"
  done
fi
log "log file: $LOG_FILE"

finish

printf '\n%s%s  Results%s\n' "$BOLD" "$BLUE" "$RESET"
for v in "${VERDICTS[@]}"; do
  printf '  %s%s%s\n' "$DIM" "$v" "$RESET"
done
printf '\n  %sLog written to:%s %s\n' "$BOLD" "$RESET" "$LOG_FILE"
printf '  %sSend this file to the maintainer — it is the only thing they need.%s\n\n' "$GREEN" "$RESET"
